<a href="https://colab.research.google.com/github/Muhammadjon1211/ai_foundation/blob/master/student_perfomance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("/content/StudentsPerformance.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Columns name:", df.columns.tolist())

print("First 5 rows:")
print(df.head)

print("Summary statistics:")
print(df.describe())

print("Missing values:")
print(df.isnull().sum())

Dataset shape (rows, columns): (1000, 8)
Columns name: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
First 5 rows:
<bound method NDFrame.head of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>
Summary statistics:
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000
Missing values:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [14]:
print("Average score by columns:")
df[['math score', 'reading score', 'writing score']].mean()

Average score by columns:

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [15]:
print("Average score by columns:")
df[['math score', 'reading score', 'writing score']].min()

Average score by columns:

math score        0
reading score    17
writing score    10
dtype: int64

In [16]:
print("Average score by columns:")
df[['math score', 'reading score', 'writing score']].max()

Average score by columns:

math score       100
reading score    100
writing score    100
dtype: int64

In [17]:
#Correlation
print("Correlation:")
df[['math score', 'reading score', 'writing score']].corr()

Correlation:

               math score  reading score  writing score
math score       1.000000       0.817580       0.802642
reading score    0.817580       1.000000       0.954598
writing score    0.802642       0.954598       1.000000

In [18]:
df["total score"] = df[["math score", "reading score", "writing score"]].sum(axis=1)
df["average score"] = df['total score'] / 3
df['passed'] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview  (total, average, passed)")
print(df[["total score", "average score", "passed"]].head())

New columns preview  (total, average, passed)
   total score  average score passed
0          218      72.666667    Yes
1          247      82.333333    Yes
2          278      92.666667    Yes
3          148      49.333333     No
4          229      76.333333    Yes

In [23]:
test_prep_group = df.groupby("test preparation course")[["math score", "reading score", "writing score"]].mean()
print("students score by test preparation course:")
print(test_prep_group)

#gender-based average
gender_avg = df.groupby("gender")[["math score", "reading score", "writing score"]].mean()
print("students score by gender:")
print(gender_avg)

#who passed vs failed
pass_rate = df['passed'].value_counts(normalize=True) * 100
print("Pass rate:")
print(pass_rate)

students score by test preparation course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
students score by gender:
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
Pass rate:
passed
Yes    89.7
No     10.3
Name: proportion, dtype: float64

In [25]:
# convert scores to numpy array
scores = df[['math score', 'reading score', 'writing score']].values

#mean, std
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

#z-score (normalize)
z_scores = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores:")
print(z_scores)

Numpy Mean: [66.089 69.169 68.054]
Numpy Std: [15.15549666 14.59289002 15.18805728]
Z-scores:
[[ 0.39002351  0.19399858  0.39149181]
 [ 0.19207553  1.42747598  1.31326868]
 [ 1.57771141  1.77010859  1.64247471]
 ...
 [-0.46775108  0.12547206 -0.20107904]
 [ 0.12609287  0.60515772  0.58901542]
 [ 0.71993682  1.15336989  1.18158627]]

In [27]:
# how many students scored above 90 average
top_scores = df[df["average score"]>=90]
print("Top scored students above 90:", len(top_scores))

failed = df[df["passed"] == "No"]
print("Failed students:", len(failed))

Top scored students above 90: 52
Failed students: 103